title = "mary.zone"
description = "Software, hacking, tea and gay"
base_url = "https://mary.zone/"
author = "Mary Guillemard"
compile_sass = false
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"

[markdown]
highlight_code = true

[extra]
twitter_handle = "marysaka_"
subpage_title = "Mary"
