title = "mary.zone"
description = "Software, hacking, tea and gay"
base_url = "https://mary.zone/"
author = "marysaka"
compile_sass = false
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
twitter_handle = "marysaka_"
main_title = "Mary (marysaka)"
subpage_title = "Mary"
