title = "mary.zone"
base_url = "https://mary.zone/"
compile_sass = true
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
twitter_handle = "marysaka_"
